name: "Deploy `main` branch to GitHub Pages"
run-name: "Deploy `main` (sha: ${{ github.sha }}) to Pages"

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  deploy:
    name: Deploy `main`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch 
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          # actions/setup-python recommends that python-version be fixed so that workflow runs are more 
          # predictable.
          python-version: '3.12.7'

      - name: Upgrade pip (Python package manager) version
        run: pip install --upgrade pip

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Install pymdown-extensions
        run: pip install pymdown-extensions

      - name: Install mkdocs-material
        run: pip install mkdocs-material

      # This step force-pushes the docs to the "gh-pages" branch of the parallelchain-docs repo.
      - name: Build and deploy documentation
        run: mkdocs gh-deploy --force